/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Component;

import java.util.function.BiConsumer;
import javax.swing.AbstractButton;

/**
 *
 * @author dvtuong
 */
public class ToggleItem extends javax.swing.JPanel {

    /**
     * Creates new form AddGroupItem
     */
    public BiConsumer<String, Boolean> on_click;
    public String username, on_txt, off_txt;
    public ToggleItem(String name, boolean on, String on_txt, String off_txt, BiConsumer<String, Boolean> on_click) {
        initComponents();
        this.on_click = on_click;
        this.username = name;
        this.on_txt = on_txt;
        this.off_txt = off_txt;
        this.name_label.setText(name);
        this.btn.setSelected(on);
        if (on) this.btn.setText(on_txt);
        else this.btn.setText(off_txt);
    }
    public void change_state(boolean on) {
        btn.setSelected(on);
        this.on_click.accept(this.username, on);
        if (on) this.btn.setText(on_txt);
        else this.btn.setText(off_txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        btn = new javax.swing.JToggleButton();
        name_label = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(32767, 48));
        setMinimumSize(new java.awt.Dimension(150, 48));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-person-48.png"))); // NOI18N

        btn.setText("Add");
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        name_label.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(btn)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        AbstractButton abstractButton = (AbstractButton) evt.getSource();
        boolean on = abstractButton.getModel().isSelected();
        this.on_click.accept(this.username, on);
        if (on) this.btn.setText(on_txt);
        else this.btn.setText(off_txt);
    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel name_label;
    // End of variables declaration//GEN-END:variables
}
